### ISSUE TITLE
Random error from Oceanic.js

### ISSUE THREAD

**Issue by NotDemonix** [OceanicJS/Oceanic#82]
```
/home/container/node_modules/oceanic.js/dist/lib/structures/Message.js:125
        if (data.attachments.length !== 0) {
                             ^

TypeError: Cannot read properties of undefined (reading 'length')
    at new Message (/home/container/node_modules/oceanic.js/dist/lib/structures/Message.js:125:30)
    at TypedCollection.update (/home/container/node_modules/oceanic.js/dist/lib/util/TypedCollection.js:54:29)
    at Shard.onDispatch (/home/container/node_modules/oceanic.js/dist/lib/gateway/Shard.js:715:52)
    at Shard.onPacket (/home/container/node_modules/oceanic.js/dist/lib/gateway/Shard.js:1055:27)
    at Shard.onWSMessage (/home/container/node_modules/oceanic.js/dist/lib/gateway/Shard.js:1243:29)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/home/container/node_modules/ws/lib/receiver.js:459:17)

Node.js v19.9.0
```
Using Oceanic 1.7.1
It's erroring very randomly but often.

**Comment by DonovanDMC** [comment]
We've already been discussing this in Discord
